services:
  apex:
    container_name: apex
    restart: always
    build:
      context: ./apex/
      dockerfile: apex.Dockerfile
    env_file:
      - ./apex/.env
    ports:
      - 6969:6969
    depends_on:
      - kafka
      - postgres

  stellar:
    container_name: stellar
    restart: always
    env_file:
      - ./stellar/.env
    build:
      context: ./stellar/
      dockerfile: stellar.Dockerfile
    depends_on:
      - mongo
      - kafka

  nimbus:
    container_name: nimbus
    restart: always
    build:
      context: ./nimbus/
      dockerfile: nimbus.Dockerfile
    ports:
      - 4200:4200

  catalyst:
    container_name: catalyst
    restart: always
    build:
      context: ./catalyst/
      dockerfile: catalyst.Dockerfile
    env_file: 
      - ./catalyst/.env
    depends_on:
      - kafka

  postgres:
    container_name: postgres
    image: debezium/postgres:13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=cooldb123
      - POSTGRES_DB=showoff
    ports:
      - 5432:5432

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cooldb123
    volumes:
      - ./vol/mongo:/data/db
    ports:
      - 27017:27017

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - 9092:9092

  debezium:
    container_name: debezium
    image: debezium/connect
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
    ports:
      - 8083:8083
