import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <div className="text-blue-500">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className="">This is Nikit</h1> 
            <h1 className="">This is Nikit</h1> 
        </div>
    )
}

export default Home
