user sudonick;
events {
  worker_connections 4096;
}
http {
  server {
    listen 3000;
    # listen [::]:3000;
    root /home/sudonick/Desktop/mycode/showoff/static/;
    location / {
      index index.js index.html;
    }
  }
}
