version: '3'

networks:
  showoff-network:
    driver: bridge

services:

  email_service:
    container_name: showoff-email-service
    restart: always
    build:
      context: . 
      dockerfile: email.Dockerfile
    volumes:
      - .:/showoff/user_service
    environment:
      - ENV=development
    ports:
      - 6969:6969
    networks:
      - showoff-network
